### ISSUE TITLE
Colors file

### ISSUE THREAD

**Issue by AmeeraAlotaibi** [mallollaa/WEDDING_Flutter#14]
I noticed that you separated your colors in a file on their own which is great! But, we usually just don't leave variables like this hanging on their own like that. 

```
Color background = Color(0xfff6f4fa);
Color maincolor = Color(0xff3F3244);
Color litecolor = Color(0xfff705B67);
Color font = Color(0xfff2F2235);
```

The best practice is if you created a class and called it for example `MyColors `and defined all the colors you want to use in your application in here using the static keyword before every variable like so:

```
class MyColors {
  static final Color background = Color(0xfff6f4fa);
  static final Color mainColor = Color(0xff3F3244);
  static final Color lightColor = Color(0xff705B67);
  static final Color fontColor = Color(0xff2F2235);
}

```

**Comment by mallollaa** [comment]
thankkk you I was sure something was missing
